name: Build Vision Pro App (macOS 15, xros2.0)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15  # 👈 Use GitHub-hosted macOS 15 runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Available Xcode Versions
        run: |
          echo "🔍 Checking available Xcode versions..."
          ls /Applications | grep Xcode || echo "⚠️ No Xcode versions found in /Applications"

      - name: Select Xcode 16.2 (Latest VisionOS Support)
        run: |
          echo "🔄 Switching to Xcode 16.2..."
          sudo xcode-select -s /Applications/Xcode_16.2.app || { 
            echo "❌ Failed to switch Xcode version!";
            exit 1;
          }

      - name: Verify Xcode Selection
        run: |
          echo "📌 Currently selected Xcode version:"
          xcode-select -p
          xcodebuild -version

      - name: Check for VisionOS 2.0 SDK
        run: |
          echo "🔎 Checking available SDKs..."
          xcodebuild -showsdks
          if ! xcodebuild -showsdks | grep -q "xros2.0"; then
            echo "❌ VisionOS 2.0 SDK (xros2.0) not found!";
            echo "🛠️ Ensure that GitHub runners have the latest Xcode with VisionOS 2.0.";
            exit 1;
          else
            echo "✅ VisionOS 2.0 SDK (xros2.0) is installed!";
          fi

      - name: Create Vision Pro Project
        run: |
          mkdir VisionProApp
          cd VisionProApp

          # Create an Xcode project placeholder
          cat > VisionProApp.xcodeproj <<EOF
          {}
          EOF

          # Create main.swift
          mkdir -p VisionProApp
          cat > VisionProApp/main.swift <<EOF
          import SwiftUI
          @main
          struct VisionProApp: App {
              var body: some Scene {
                  WindowGroup {
                      Text("Hello, Vision Pro 2.0!")
                          .padding()
                  }
              }
          }
          EOF

          # Create Info.plist
          cat > VisionProApp/Info.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleIdentifier</key>
              <string>com.example.visionproapp</string>
              <key>CFBundleName</key>
              <string>VisionProApp</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>UILaunchStoryboardName</key>
              <string>Main</string>
          </dict>
          </plist>
          EOF

      - name: Build Vision Pro App
        run: |
          cd VisionProApp
          echo "🚀 Starting build process..."
          xcodebuild clean build \
            -project VisionProApp.xcodeproj \
            -scheme VisionProApp \
            -sdk xros2.0 \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | tee build_log.txt || { 
              echo "❌ Build failed! See logs below:";
              cat build_log.txt;
              exit 1;
            }

      - name: Archive Vision Pro App
        run: |
          cd VisionProApp
          xcodebuild archive \
            -project VisionProApp.xcodeproj \
            -scheme VisionProApp \
            -sdk xros2.0 \
            -configuration Debug \
            -archivePath build/VisionProApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export Vision Pro App (Unsigned)
        run: |
          cd VisionProApp
          mkdir -p build/output
          xcodebuild -exportArchive \
            -archivePath build/VisionProApp.xcarchive \
            -exportPath build/output \
            -exportOptionsPlist <(echo '{}') || true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VisionProApp
          path: VisionProApp/build/output
