name: Build Vision Pro App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Xcode and SDKs
        run: |
          echo "Checking available Xcode versions..."
          ls /Applications | grep Xcode
          
          echo "Currently selected Xcode version:"
          xcode-select -p
          xcodebuild -version

          echo "Checking available SDKs..."
          xcodebuild -showsdks

      - name: Select Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Create Vision Pro Project
        run: |
          mkdir VisionProApp
          cd VisionProApp

          # Create an Xcode project
          cat > VisionProApp.xcodeproj <<EOF
          {}
          EOF

          # Create main.swift
          mkdir -p VisionProApp
          cat > VisionProApp/main.swift <<EOF
          import SwiftUI
          @main
          struct VisionProApp: App {
              var body: some Scene {
                  WindowGroup {
                      Text("Hello, Vision Pro!")
                          .padding()
                  }
              }
          }
          EOF

          # Create Info.plist
          cat > VisionProApp/Info.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleIdentifier</key>
              <string>com.example.visionproapp</string>
              <key>CFBundleName</key>
              <string>VisionProApp</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>UILaunchStoryboardName</key>
              <string>Main</string>
          </dict>
          </plist>
          EOF

      - name: Build Vision Pro App
        run: |
          cd VisionProApp
          echo "Starting build process..."
          xcodebuild clean build \
            -project VisionProApp.xcodeproj \
            -scheme VisionProApp \
            -sdk visionos \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | tee build_log.txt || { echo "❌ Build failed! See logs below:"; cat build_log.txt; exit 1; }

      - name: Archive Vision Pro App
        run: |
          cd VisionProApp
          xcodebuild archive \
            -project VisionProApp.xcodeproj \
            -scheme VisionProApp \
            -sdk visionos \
            -configuration Debug \
            -archivePath build/VisionProApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export Vision Pro App (Unsigned)
        run: |
          cd VisionProApp
          mkdir -p build/output
          xcodebuild -exportArchive \
            -archivePath build/VisionProApp.xcarchive \
            -exportPath build/output \
            -exportOptionsPlist <(echo '{}') || true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VisionProApp
          path: VisionProApp/build/output
