name: Build Vision Pro App (Verbose Debugging)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Available SDKs
        run: |
          echo "Checking available SDKs..."
          xcodebuild -showsdks || echo "⚠️ Failed to list available SDKs"

      - name: Debug Available Xcode Versions
        run: |
          echo "Checking available Xcode versions..."
          ls /Applications | grep Xcode || echo "⚠️ No Xcode versions found in /Applications"

      - name: Select Xcode Version
        run: |
          echo "Switching to Xcode 15..."
          sudo xcode-select -s /Applications/Xcode_15.2.app || echo "⚠️ Failed to switch Xcode version"

      - name: Confirm Xcode Version
        run: |
          echo "Currently selected Xcode version:"
          xcode-select -p || echo "⚠️ Failed to retrieve Xcode path"
          xcodebuild -version || echo "⚠️ Failed to retrieve Xcode version"

      - name: Create Vision Pro Project
        run: |
          mkdir VisionProApp
          cd VisionProApp
          
          # Create main.swift
          mkdir -p VisionProApp
          cat > VisionProApp/main.swift <<EOF
          import SwiftUI
          @main
          struct VisionProApp: App {
              var body: some Scene {
                  WindowGroup {
                      Text("Hello, Vision Pro!")
                          .padding()
                  }
              }
          }
          EOF

          # Create Info.plist
          cat > VisionProApp/Info.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleIdentifier</key>
              <string>com.example.visionproapp</string>
              <key>CFBundleName</key>
              <string>VisionProApp</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>UILaunchStoryboardName</key>
              <string>Main</string>
          </dict>
          </plist>
          EOF

      - name: Build Vision Pro App (Verbose Logging)
        run: |
          cd VisionProApp
          echo "Starting build process..."
          xcodebuild clean build \
            -project VisionProApp.xcodeproj \
            -scheme VisionProApp \
            -sdk visionos \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | tee build_log.txt || { echo "❌ Build failed! See logs below:"; cat build_log.txt; exit 1; }

      - name: Upload Build Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: VisionProApp/build_log.txt
