name: Build Vision Pro App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15  # Use macOS 15 runner for VisionOS compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install xcodegen
        run: |
          echo "Installing xcodegen..."
          brew install xcodegen

      - name: Prepare Project Structure
        run: |
          echo "Setting up project structure..."
          mkdir -p VisionProApp/Sources
          mkdir -p VisionProApp/Resources

          # Create Swift source files
          cat <<EOF > VisionProApp/Sources/ContentView.swift
          import SwiftUI

          struct ContentView: View {
              var body: some View {
                  Text("Hello, Vision Pro!")
              }
          }
          EOF

          cat <<EOF > VisionProApp/Sources/VisionProApp.swift
          import SwiftUI

          @main
          struct VisionProApp: App {
              var body: some Scene {
                  WindowGroup {
                      ContentView()
                  }
              }
          }
          EOF

          # Create Info.plist
          cat <<EOF > VisionProApp/Resources/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key>
              <string>VisionProApp</string>
              <key>CFBundleIdentifier</key>
              <string>com.example.VisionProApp</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>UILaunchStoryboardName</key>
              <string>LaunchScreen</string>
          </dict>
          </plist>
          EOF

      - name: Generate Xcode Project
        run: |
          echo "Generating Xcode project..."
          cd VisionProApp

          # Create xcodegen spec
          cat <<EOF > project.yml
          name: VisionProApp
          options:
            bundleIdPrefix: com.example
          targets:
            VisionProApp:
              type: application
              platform: visionOS
              deploymentTarget: '1.0'
              sources: [Sources]
              resources: [Resources/Info.plist]
              info:
                path: Resources/Info.plist
          EOF

          # Generate the Xcode project
          xcodegen generate

      - name: Select Xcode 16.2
        run: |
          echo "Switching to Xcode 16.2..."
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcodebuild -version

      - name: Verify VisionOS SDK
        run: |
          echo "Checking available SDKs..."
          if ! xcodebuild -showsdks | grep -q "xros"; then
            echo "VisionOS SDK not found!"
            exit 1
          else
            echo "VisionOS SDK is available."
          fi

      - name: Build Vision Pro App
        run: |
          cd VisionProApp
          echo "Building Vision Pro App..."
          xcodebuild clean build \
            -project VisionProApp.xcodeproj \
            -scheme VisionProApp \
            -sdk xros \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Archive Vision Pro App
        run: |
          cd VisionProApp
          echo "Archiving Vision Pro App..."
          xcodebuild archive \
            -project VisionProApp.xcodeproj \
            -scheme VisionProApp \
            -sdk xros \
            -configuration Release \
            -archivePath build/VisionProApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create ExportOptions.plist
        run: |
          echo "Creating ExportOptions.plist..."
          cat <<EOF > VisionProApp/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Export Vision Pro App
        run: |
          cd VisionProApp
          echo "Exporting Vision Pro App..."
          xcodebuild -exportArchive \
            -archivePath build/VisionProApp.xcarchive \
            -exportPath build/output \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VisionProApp
          path: VisionProApp/build/output
