name: Build Vision Pro App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15  # Use macOS 15 runner for VisionOS compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: |
          echo "Switching to Xcode 16.2..."
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcodebuild -version

      - name: Verify VisionOS 2.2 SDK
        run: |
          echo "Checking available SDKs..."
          if ! xcodebuild -showsdks | grep -q "xros2.2"; then
            echo "VisionOS 2.2 SDK (xros2.2) not found!"
            exit 1
          else
            echo "VisionOS 2.2 SDK (xros2.2) is available."
          fi

      - name: Build Vision Pro App
        run: |
          echo "Building Vision Pro App..."
          xcodebuild clean build \
            -scheme VisionProApp \
            -sdk xros2.2 \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Archive Vision Pro App
        run: |
          echo "Archiving Vision Pro App..."
          xcodebuild archive \
            -scheme VisionProApp \
            -sdk xros2.2 \
            -configuration Release \
            -archivePath build/VisionProApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export Vision Pro App
        run: |
          echo "Exporting Vision Pro App..."
          xcodebuild -exportArchive \
            -archivePath build/VisionProApp.xcarchive \
            -exportPath build/output \
            -exportOptionsPlist <(echo '{}')

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VisionProApp
          path: build/output
