name: Build Vision Pro App (macOS 15, xros2.2)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15  # 👈 GitHub-hosted macOS 15 runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Available Xcode Versions
        run: |
          echo "🔍 Checking available Xcode versions..."
          ls /Applications | grep Xcode || echo "⚠️ No Xcode versions found in /Applications"

      - name: Select Xcode 16.2 (Latest VisionOS Support)
        run: |
          echo "🔄 Switching to Xcode 16.2..."
          sudo xcode-select -s /Applications/Xcode_16.2.app || { 
            echo "❌ Failed to switch Xcode version!";
            exit 1;
          }

      - name: Verify Xcode Selection
        run: |
          echo "📌 Currently selected Xcode version:"
          xcode-select -p
          xcodebuild -version

      - name: Check for VisionOS 2.2 SDK
        run: |
          echo "🔎 Checking available SDKs..."
          xcodebuild -showsdks
          if ! xcodebuild -showsdks | grep -q "xros2.2"; then
            echo "❌ VisionOS 2.2 SDK (xros2.2) not found!";
            echo "🛠️ Ensure that GitHub runners have the latest Xcode with VisionOS 2.2.";
            exit 1;
          else
            echo "✅ VisionOS 2.2 SDK (xros2.2) is installed!";
          fi

      - name: Create Vision Pro Xcode Project (Properly)
        run: |
          echo "🛠️ Creating Vision Pro Xcode Project..."
          mkdir VisionProApp
          cd VisionProApp

          # Create an empty Xcode project
          mkdir VisionProApp.xcodeproj
          touch VisionProApp.xcodeproj/project.pbxproj

          echo "✅ Xcode project structure created!"

      - name: Create Vision Pro App Files
        run: |
          cd VisionProApp

  
